name: Juice Shop CI/CD Case DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

  sast_scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install semgrep
        run: |
          python -m pip install semgrep

      - name: Semgrep Scan
        continue-on-error: true
        run: |
          mkdir -p results
          semgrep --config auto --json > results/semgrep_results.json 

  sca_scan:
    runs-on: ubuntu-latest
    needs: sast_scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Dependency-Check
        run: |
          VERSION=$(curl -s https://jeremylong.github.io/DependencyCheck/current.txt)
          curl -Ls "https://github.com/jeremylong/DependencyCheck/releases/download/v${VERSION}/dependency-check-${VERSION}-release.zip" --output dependency-check.zip
          unzip dependency-check.zip -d dependency-check
          rm dependency-check.zip

      - name: Run OWASP Dependency Check
        run: |
          mkdir -p results
          ./dependency-check/bin/dependency-check.sh --project "Juice Shop" --scan . --format JSON --out results/dependency-check-report.json || true

  container_scan:
    runs-on: ubuntu-latest
    needs: sca_scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build the Container image
        run: docker build . --file Dockerfile --tag localbuild/juice:latest

      - name: Scan container image with Anchore
        uses: anchore/scan-action@v3
        with:
          image: "localbuild/juice:latest"

      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

  secret_scan:
    runs-on: ubuntu-latest
    needs: container_scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Gitleaks
        continue-on-error: true
        uses: zricethezav/gitleaks-action@v1.1.5
        with:
          args: "--path . --report-format json --report-path results/gitleaks-results.json"

  upload_results:
    runs-on: ubuntu-latest
    needs: [build, sast_scan, sca_scan, container_scan, secret_scan]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload SAST results
        run: cp results/semgrep_results.json results/

      - name: Upload SCA results
        run: cp results/dependency-check-report.json results/

      - name: Upload Container Scan results
        run: cp results/*.json results/grype-results.json

      - name: Upload Secret Scan results
        run: cp results/gitleaks-results.json results/

      - name: Upload results to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results/semgrep_results.json
